### ISSUE TITLE
Remove optional from Command Parameters

### ISSUE THREAD

**Issue by JavierRefuerzo** [UniversalDevicesInc-PG3/udi-poly-notification#39]
I think all values should not be optional as sending command without any params results in error.   

```
<!--  Pushover Node  -->
<nodeDef id="pushover_PushOver" nls="pov">
<editors/>
.....

<cmd id="GV10">
<p id="Device" editor="PO_D_PushOver" init="GV1" optional="T"/>
<p id="Priority" editor="PO_PRIORITY" init="GV2" optional="T"/>
<p id="Format" editor="PO_FORMAT" init="GV3" optional="T"/>
<p id="Sound" editor="PO_S_PushOver" init="GV6" optional="T"/>
<p id="Retry" editor="PO_RETRY" init="GV4" optional="T"/>
<p id="Expire" editor="PO_EXPIRE" init="GV5" optional="T"/>
<p id="Content" editor="_sys_notify_short" optional="T"/>
</cmd>
```

**Comment by jimboca** [comment]
It should not be an error. They are optional because by default it will use the current node settings.

**Comment by JavierRefuerzo** [comment]
Possibly related to #37 .  Will retry when fixed.

**Comment by JavierRefuerzo** [comment]
Looking at this again I think the 'Content"   can not be optional as there is no init value.

**Comment by jimboca** [comment]
It is optional because the nodeserver will grab the current values set.  For example GV1 will use the current "Device" set on the node if it's not passed in by "Send Sys Short With Params".  The Content can not have a driver because it's the _sys_notify_short, but the node server stores internally the value when you set it with "Short Custom Content".  But if you never set it after the node server has been restarted then it will send "None", so it may make more sense to never make that one optional...
